[package]
name = "mypipe"
version = "0.1.1"
authors = ["Franck AUbry AL2"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
